version: '3'
services:
  validate:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./:/opt/imagegenerator
    ports:
      - "8080:8080"
